comment: |
  As described in the issue template, issues missing the required info will be closed.
  Please open a new issue providing the nessesarry information.
issueConfigs:
- content:
  - "Describe the bug"
  - "To Reproduce"
  - "Expected behavior"
  - "Additional context"